BEGIN;

CREATE TABLE IF NOT EXISTS expense_types (
  expense_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_type_name VARCHAR(100) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO expense_types (expense_type_name)
VALUES
  ('Salary'),
  ('Rent'),
  ('Travel'),
  ('Fuel'),
  ('Stationery'),
  ('Bank Charges'),
  ('Office Expense'),
  ('Collection Expense'),
  ('Maintenance'),
  ('Other Expense')
ON CONFLICT (expense_type_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS expenses (
  expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date DATE NOT NULL,
  expense_type_id BIGINT NOT NULL REFERENCES expense_types(expense_type_id),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  paid_to VARCHAR(120),
  paid_by VARCHAR(120),
  payment_mode VARCHAR(50),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_expenses_expense_date
  ON expenses (expense_date DESC);

CREATE INDEX IF NOT EXISTS idx_expenses_expense_type_id
  ON expenses (expense_type_id);

CREATE INDEX IF NOT EXISTS idx_expenses_paid_by
  ON expenses (paid_by);

COMMIT;
