BEGIN;

CREATE TABLE IF NOT EXISTS income_types (
  income_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  income_type_name VARCHAR(80) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO income_types (income_type_name)
VALUES
  ('Interest Received'),
  ('Processing Fee'),
  ('Penalty'),
  ('Document Charge'),
  ('Other Loan Income')
ON CONFLICT (income_type_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS loan_income (
  loan_income_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id VARCHAR(40) NOT NULL,
  customer_id VARCHAR(40) NOT NULL,
  income_type_id BIGINT NOT NULL REFERENCES income_types(income_type_id),
  income_date DATE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  received_by VARCHAR(120),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loan_income_loan_id
  ON loan_income (loan_id);

CREATE INDEX IF NOT EXISTS idx_loan_income_customer_id
  ON loan_income (customer_id);

CREATE INDEX IF NOT EXISTS idx_loan_income_income_date
  ON loan_income (income_date DESC);

CREATE INDEX IF NOT EXISTS idx_loan_income_income_type_id
  ON loan_income (income_type_id);

COMMIT;
