BEGIN;

CREATE TABLE IF NOT EXISTS income_types (
  income_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  income_type_name VARCHAR(80) NOT NULL UNIQUE,
  requires_loan BOOLEAN NOT NULL DEFAULT FALSE,
  affects_profit BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO income_types (income_type_name, requires_loan, affects_profit)
VALUES
  ('Interest Received', TRUE, TRUE),
  ('Processing Fee', FALSE, TRUE),
  ('Penalty', FALSE, TRUE),
  ('Document Charge', FALSE, TRUE),
  ('Partner Capital', FALSE, FALSE),
  ('Partner Loan', FALSE, FALSE),
  ('Gold Pledge Cash', FALSE, FALSE),
  ('Other Receipt', FALSE, FALSE)
ON CONFLICT (income_type_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS loan_income (
  loan_income_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id VARCHAR(40),
  customer_id VARCHAR(40),
  income_type_id BIGINT NOT NULL REFERENCES income_types(income_type_id),
  income_date DATE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  received_by VARCHAR(120),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loan_income_loan_id
  ON loan_income (loan_id);

CREATE INDEX IF NOT EXISTS idx_loan_income_customer_id
  ON loan_income (customer_id);

CREATE INDEX IF NOT EXISTS idx_loan_income_income_date
  ON loan_income (income_date DESC);

CREATE INDEX IF NOT EXISTS idx_loan_income_income_type_id
  ON loan_income (income_type_id);

COMMIT;
